// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) 
// Source File Name:   DSPIBGBODYPackager.java

package vn.com.msb.as400.dsp.packager;

import vn.com.msb.as400.dsp.*;

public class DSPIBGBODYPackager extends DSPPackager
{

    public DSPIBGBODYPackager()
    {
    }

    public void declare()
    {
        DSPField fld[] = null;
        fld = (new DSPField[] {
            new DSPCharField(10, "Description for field 1"), new DSPPackedField(5, 0, "Description for field 2"), new DSPCharField(1, "Description for field 3"), new DSPPackedField(5, 0, "Description for field 4"), new DSPCharField(10, "Description for field 5"), new DSPNumericField(6, "Description for field 6"), new DSPNumericField(6, "Description for field 7"), new DSPCharField(2, "Description for field 8"), new DSPCharField(15, "Description for field 9"), new DSPCharField(10, "Description for field 10"), 
            new DSPNumericField(5, "Description for field 11"), new DSPNumericField(2, "Description for field 12"), new DSPNumericField(1, "Description for field 13"), new DSPCharField(1, "Description for field 14"), new DSPCharField(1, "Description for field 15"), new DSPCharField(1, "Description for field 16"), new DSPCharField(1, "Description for field 17"), new DSPCharField(1, "Description for field 18"), new DSPCharField(1, "Description for field 19"), new DSPCharField(1, "Description for field 20"), 
            new DSPPackedField(10, 0, "Description for field 21"), new DSPPackedField(10, 0, "Description for field 22"), new DSPPackedField(10, 0, "Description for field 23"), new DSPPackedField(10, 0, "Description for field 24"), new DSPPackedField(10, 0, "Description for field 25"), new DSPPackedField(10, 0, "Description for field 26"), new DSPPackedField(10, 0, "Description for field 27"), new DSPPackedField(10, 0, "Description for field 28"), new DSPPackedField(10, 0, "Description for field 29"), new DSPPackedField(10, 0, "Description for field 30"), 
            new DSPPackedField(10, 0, "Description for field 31"), new DSPPackedField(10, 0, "Description for field 32"), new DSPPackedField(10, 0, "Description for field 33"), new DSPPackedField(10, 0, "Description for field 34"), new DSPPackedField(10, 0, "Description for field 35"), new DSPPackedField(10, 0, "Description for field 36"), new DSPPackedField(10, 0, "Description for field 37"), new DSPPackedField(10, 0, "Description for field 38"), new DSPPackedField(10, 0, "Description for field 39"), new DSPPackedField(10, 0, "Description for field 40"), 
            new DSPPackedField(10, 0, "Description for field 41"), new DSPPackedField(10, 0, "Description for field 42"), new DSPPackedField(10, 0, "Description for field 43"), new DSPPackedField(10, 0, "Description for field 44"), new DSPPackedField(10, 0, "Description for field 45"), new DSPPackedField(10, 0, "Description for field 46"), new DSPPackedField(10, 0, "Description for field 47"), new DSPPackedField(10, 0, "Description for field 48"), new DSPPackedField(10, 0, "Description for field 49"), new DSPPackedField(10, 0, "Description for field 50"), 
            new DSPCharField(4, "Description for field 51"), new DSPPackedField(10, 0, "Description for field 52"), new DSPCharField(10, "Description for field 53"), new DSPCharField(1, "Description for field 54"), new DSPCharField(40, "Description for field 55"), new DSPCharField(20, "Description for field 56"), new DSPCharField(1, "Description for field 57"), new DSPCharField(1, "Description for field 58"), new DSPCharField(1, "Description for field 59"), new DSPCharField(1, "Description for field 60"), 
            new DSPCharField(1, "Description for field 61"), new DSPCharField(20, "Description for field 62"), new DSPCharField(4, "Description for field 63"), new DSPCharField(4, "Description for field 64"), new DSPCharField(4, "Description for field 65"), new DSPCharField(4, "Description for field 66"), new DSPCharField(4, "Description for field 67"), new DSPCharField(1, "Description for field 68"), new DSPCharField(1, "Description for field 69"), new DSPCharField(1, "Description for field 70"), 
            new DSPCharField(1, "Description for field 71"), new DSPCharField(1, "Description for field 72"), new DSPCharField(1, "Description for field 73"), new DSPCharField(1, "Description for field 74"), new DSPCharField(1, "Description for field 75"), new DSPCharField(1, "Description for field 76"), new DSPCharField(1, "Description for field 77"), new DSPCharField(1, "Description for field 78"), new DSPCharField(1, "Description for field 79"), new DSPCharField(1, "Description for field 80"), 
            new DSPCharField(1, "Description for field 81"), new DSPCharField(1, "Description for field 82"), new DSPCharField(1, "Description for field 83"), new DSPCharField(1, "Description for field 84"), new DSPCharField(1, "Description for field 85"), new DSPCharField(1, "Description for field 86"), new DSPCharField(1, "Description for field 87"), new DSPCharField(1, "Description for field 88"), new DSPCharField(1, "Description for field 89"), new DSPCharField(1, "Description for field 90"), 
            new DSPCharField(1, "Description for field 91"), new DSPCharField(1, "Description for field 92"), new DSPCharField(1, "Description for field 93"), new DSPCharField(1, "Description for field 94"), new DSPCharField(1, "Description for field 95"), new DSPCharField(1, "Description for field 96"), new DSPCharField(1, "Description for field 97"), new DSPCharField(1, "Description for field 98"), new DSPCharField(1, "Description for field 99"), new DSPCharField(1, "Description for field 100"), 
            new DSPCharField(1, "Description for field 101"), new DSPCharField(1, "Description for field 102"), new DSPCharField(1, "Description for field 103"), new DSPCharField(1, "Description for field 104"), new DSPCharField(1, "Description for field 105"), new DSPCharField(1, "Description for field 106"), new DSPCharField(1, "Description for field 107"), new DSPCharField(1, "Description for field 108"), new DSPCharField(1, "Description for field 109"), new DSPCharField(1, "Description for field 110"), 
            new DSPCharField(1, "Description for field 111"), new DSPCharField(1, "Description for field 112"), new DSPCharField(1, "Description for field 113"), new DSPCharField(1, "Description for field 114"), new DSPCharField(1, "Description for field 115"), new DSPCharField(1, "Description for field 116"), new DSPCharField(1, "Description for field 117"), new DSPCharField(1, "Description for field 118"), new DSPCharField(1, "Description for field 119"), new DSPCharField(1, "Description for field 120"), 
            new DSPCharField(1, "Description for field 121"), new DSPCharField(1, "Description for field 122"), new DSPCharField(1, "Description for field 123"), new DSPCharField(1, "Description for field 124"), new DSPCharField(1, "Description for field 125"), new DSPCharField(1, "Description for field 126"), new DSPCharField(1, "Description for field 127"), new DSPCharField(20, "Description for field 128"), new DSPCharField(20, "Description for field 129"), new DSPCharField(20, "Description for field 130"), 
            new DSPCharField(40, "Description for field 131"), new DSPPackedField(1, 0, "Description for field 132"), new DSPPackedField(10, 0, "Description for field 133"), new DSPPackedField(3, 0, "Description for field 134"), new DSPCharField(1, "Description for field 135"), new DSPPackedField(2, 0, "Description for field 136"), new DSPCharField(1, "Description for field 137"), new DSPPackedField(2, 0, "Description for field 138"), new DSPPackedField(2, 0, "Description for field 139"), new DSPPackedField(2, 0, "Description for field 140"), 
            new DSPPackedField(2, 0, "Description for field 141"), new DSPPackedField(2, 0, "Description for field 142"), new DSPPackedField(2, 0, "Description for field 143"), new DSPPackedField(2, 0, "Description for field 144"), new DSPPackedField(2, 0, "Description for field 145"), new DSPPackedField(2, 0, "Description for field 146"), new DSPPackedField(2, 0, "Description for field 147"), new DSPPackedField(2, 0, "Description for field 148"), new DSPPackedField(2, 0, "Description for field 149"), new DSPPackedField(2, 0, "Description for field 150"), 
            new DSPPackedField(2, 0, "Description for field 151"), new DSPPackedField(2, 0, "Description for field 152"), new DSPPackedField(2, 0, "Description for field 153"), new DSPPackedField(2, 0, "Description for field 154"), new DSPPackedField(2, 0, "Description for field 155"), new DSPPackedField(2, 0, "Description for field 156"), new DSPPackedField(2, 0, "Description for field 157"), new DSPPackedField(2, 0, "Description for field 158"), new DSPPackedField(2, 0, "Description for field 159"), new DSPPackedField(2, 0, "Description for field 160"), 
            new DSPPackedField(2, 0, "Description for field 161"), new DSPPackedField(2, 0, "Description for field 162"), new DSPPackedField(2, 0, "Description for field 163"), new DSPPackedField(2, 0, "Description for field 164"), new DSPPackedField(2, 0, "Description for field 165"), new DSPPackedField(2, 0, "Description for field 166"), new DSPPackedField(2, 0, "Description for field 167"), new DSPCharField(1, "Description for field 168"), new DSPCharField(1, "Description for field 169"), new DSPPackedField(3, 0, "Description for field 170"), 
            new DSPCharField(1, "Description for field 171"), new DSPCharField(1, "Description for field 172"), new DSPCharField(1, "Description for field 173"), new DSPCharField(1, "Description for field 174"), new DSPCharField(1, "Description for field 175"), new DSPCharField(1, "Description for field 176"), new DSPCharField(133, "Description for field 177"), new DSPCharField(10, "Description for field 178"), new DSPCharField(1, "Description for field 179"), new DSPCharField(1, "Description for field 180"), 
            new DSPCharField(1, "Description for field 181"), new DSPCharField(1, "Description for field 182"), new DSPCharField(1, "Description for field 183"), new DSPCharField(1, "Description for field 184"), new DSPCharField(1, "Description for field 185"), new DSPCharField(1, "Description for field 186"), new DSPCharField(1, "Description for field 187"), new DSPCharField(1, "Description for field 188"), new DSPCharField(3, "Description for field 189"), new DSPCharField(30, "Description for field 190"), 
            new DSPCharField(24, "Description for field 191"), new DSPCharField(6, "Description for field 192"), new DSPCharField(10, "Description for field 193"), new DSPCharField(22, "Description for field 194"), new DSPCharField(15, "Description for field 195"), new DSPCharField(17, "Description for field 196"), new DSPCharField(20, "Description for field 197"), new DSPCharField(20, "Description for field 198"), new DSPCharField(5, "Description for field 199"), new DSPPackedField(10, 0, "Description for field 200"), 
            new DSPCharField(1, "Description for field 201"), new DSPCharField(1, "Description for field 202"), new DSPPackedField(1, 0, "Description for field 203"), new DSPCharField(30, "Description for field 204"), new DSPCharField(15, "Description for field 205"), new DSPCharField(35, "Description for field 206"), new DSPCharField(35, "Description for field 207"), new DSPCharField(35, "Description for field 208"), new DSPCharField(11, "Description for field 209"), new DSPPackedField(8, 0, "Description for field 210"), 
            new DSPPackedField(8, 0, "Description for field 211"), new DSPPackedField(4, 0, "Description for field 212")
        });
        addBody("IBGBODY".toUpperCase(), fld);
    }
}
