package vn.com.msb.cnn.utils;

import java.util.HashMap;

public class ErrorConstants {

	private static HashMap<String, String> errorCodeMap = new HashMap<String, String>();

	static {
		errorCodeMap.put("1", "SO TK KHONG TIM THAY");
		errorCodeMap.put("2", "TK DA BI PHONG TOA");
		errorCodeMap.put("3", "ALERT/SPEC INSTR");
		errorCodeMap.put("4", "NSF ITEMS TODAY");
		errorCodeMap.put("5", "KHONG DU SO DU");
		errorCodeMap.put("6", "TK MOI");
		errorCodeMap.put("7", "TK DA BI DONG");
		errorCodeMap.put("8", "TK KHONG HD");
		errorCodeMap.put("9", "RESTRICTED A/C");
		errorCodeMap.put("10", "FROZEN ACCOUNT");
		errorCodeMap.put("11", "UPDATE PASSBK FIRST");
		errorCodeMap.put("12", "INSIDER ACCOUNT");
		errorCodeMap.put("13", "TK DEN HAN");
		errorCodeMap.put("14", "SO DU NHO HON SD TOI THIEU");
		errorCodeMap.put("15", "AMOUNT > PAYOFF");
		errorCodeMap.put("16", "QUA SO DU");
		errorCodeMap.put("17", "FROZEN OR ZERO ACCRL ACCT");
		errorCodeMap.put("18", "AMOUNT > ACCRUED INTEREST");
		errorCodeMap.put("19", "NGUNG THANH TOAN");
		errorCodeMap.put("20", "SO TIEN GD > SO DU GOC");
		errorCodeMap.put("21", "DISCOUNTED NOTE");
		errorCodeMap.put("22", "TXN > OVERDUE INT");
		errorCodeMap.put("23", "TXN > OTHER CHARGES");
		errorCodeMap.put("24", "TXN NOT STD PMT");
		errorCodeMap.put("25", "NO TXN ALLOWED");
		errorCodeMap.put("26", "TXN > ACCRD INT");
		errorCodeMap.put("27", "EFF DATE BEFORE 1ST DRAW DOWN");
		errorCodeMap.put("28", "LOAI TIEN KO KHOP");
		errorCodeMap.put("29", "POST-DATED TRANSACTION EXIST");
		errorCodeMap.put("30", "INVALID GROUP FOR ACCOUNT");
		errorCodeMap.put("32", "DISPLAY STATUS MESG");
		errorCodeMap.put("33", "DECEASED CUSTOMER");
		errorCodeMap.put("34", "SO TT DAU KO TIM THAY");
		errorCodeMap.put("35", "LOAI TIEN KO DUNG");
		errorCodeMap.put("36", "TK DA TON TAI");
		errorCodeMap.put("37", "SP KHONG TIM THAY");
		errorCodeMap.put("38", "KHONG TIM THAY CIF");
		errorCodeMap.put("39", "SO SEC SAI");
		errorCodeMap.put("40", "STOP PAYMT SUSPECT");
		errorCodeMap.put("41", "COLLECTION ITEM NOT FOUND/UNMATCHED");
		errorCodeMap.put("42", "SO TK KHONG THAY");
		errorCodeMap.put("43", "SO TK DA TON TAI");
		errorCodeMap.put("44", "NO OD/OC FACILITY");
		errorCodeMap.put("45", "DA CO GD HOM NAY");
		errorCodeMap.put("46", "FLOAT NOT ZERO FOR CLOSEOUT");
		errorCodeMap.put("47", "ODP NOT ZERO FOR CLOSEOUT");
		errorCodeMap.put("48", "TK BI DONG HOM NAY");
		errorCodeMap.put("49", "AMT MUST = W/D INT");
		errorCodeMap.put("50", "INCORRECT CLOSEOUT");
		errorCodeMap.put("51", "SO SEC = 0");
		errorCodeMap.put("52", "NGAY HIEU LUC KO DUNG");
		errorCodeMap.put("53", "CLOSEOUT IS NOT WITHIN LIMITS");
		errorCodeMap.put("54", "TXN DOES NOT MATCH ORIGINAL");
		errorCodeMap.put("55", "Passbook Record Not Found");
		errorCodeMap.put("56", "NO OCP FACILITY EXISTS");
		errorCodeMap.put("57", "EXCEED AUTH LIMIT");
		errorCodeMap.put("58", "MUST USE OD/OC FACILITY");
		errorCodeMap.put("59", "INSUFFICIENT FLT");
		errorCodeMap.put("60", "HOLD AMT/CHECK# MISMATCH");
		errorCodeMap.put("61", "NOT A PASSBOOK A/C");
		errorCodeMap.put("62", "EXCEEDS DRAWING LIMIT");
		errorCodeMap.put("63", "LOAN EXPIRED");
		errorCodeMap.put("64", "ORIGINAL LN TXN NOT FOUND");
		errorCodeMap.put("65", "NO LOAN RELEASE YET");
		errorCodeMap.put("66", "NOT YEARLY REST/HP/BD");
		errorCodeMap.put("67", "TRAN > INT-IN-ADVANCE BAL");
		errorCodeMap.put("68", "REVOLV TRANS NOT EVEN 1000");
		errorCodeMap.put("69", "AVAILABILITY DATE EXPIRED");
		errorCodeMap.put("70", "TXN > MISC COST");
		errorCodeMap.put("71", "TXN > 3 PAYMENTS");
		errorCodeMap.put("72", "LN NOT FULLY RELEASED YET");
		errorCodeMap.put("73", "HAD PREVIOUS PAYMENT TODAY");
		errorCodeMap.put("74", "PAYOFF NOT WITHIN LIMIT");
		errorCodeMap.put("75", "CHARGED OFF LOAN");
		errorCodeMap.put("76", "SOLD PARTICIPATION");
		errorCodeMap.put("77", "SO SERI SO TK SAI");
		errorCodeMap.put("78", "TK CO TIEN ICH AFT");
		errorCodeMap.put("79", "NGAY DAO HAN KO = NGAY GD");
		errorCodeMap.put("80", "NGAY DAO HAN KO > NGAY GD");
		errorCodeMap.put("81", "DISBURSE AMT <> S&P SCHEDULE");
		errorCodeMap.put("82", "PLACEMENT AMT > PRODUCT LIMIT");
		errorCodeMap.put("83", "CONV INT TO ISLAMIC NOT ALLOW");
		errorCodeMap.put("84", "DISBURSE AMOUNT EXCEEDS");
		errorCodeMap.put("85", "DRAWDOWN AMT <> AVAIL BALANCE");
		errorCodeMap.put("86", "TRANS AMT GREATER THAN");
		errorCodeMap.put("87", "KINDLY CHECK THE RETENTION SUM");
		errorCodeMap.put("88", "NOT WITHIN AGE LIMIT");
		errorCodeMap.put("89", "LOAN DISBURSEMENT NOT ALLOW");
		errorCodeMap.put("90", "HAVE ARREAR OUTSTANDING AMT");
		errorCodeMap.put("91", "RELEASE AMOUNT > DEALER FAC LIMITS");
		errorCodeMap.put("92", "RELEASE AMT > FBT/FBR LIMIT");
		errorCodeMap.put("93", "ONLY 1ST CASH/HC/LC  DEP ALLOWED");
		errorCodeMap.put("120", "FIRST DEP < INITIAL AMT");
		errorCodeMap.put("121", "STATUS CHG DEMAND DEPOSIT ONLY");
		errorCodeMap.put("122", "SO DU KO LA O");
		errorCodeMap.put("123", "TK DA BI DONG");
		errorCodeMap.put("124", "TRANG THAI DA THAY DOI TRUOC");
		errorCodeMap.put("125", "TRANG THAI KO LA KO HD");
		errorCodeMap.put("126", "TRANG THAI LA KO DONG");
		errorCodeMap.put("127", "TRANG THAI TK KO DUNG");
		errorCodeMap.put("128", "HAS ACTIVE ODP... CANNOT CLOSE");
		errorCodeMap.put("129", "THE DA PHAT HANH");
		errorCodeMap.put("130", "NO NEW DEP ON ACTIVE FD");
		errorCodeMap.put("131", "INVALID BOP CODE-EXT A/C");
		errorCodeMap.put("132", "GD LIEN CN");
		errorCodeMap.put("133", "ACCOUNT HAS HOLD MAIL");
		errorCodeMap.put("134", "SO SERI KHONG DUNG");
		errorCodeMap.put("135", "NON-PERFORMING STATUS");
		errorCodeMap.put("136", "NOT NON-PERFORMING STATUS");
		errorCodeMap.put("137", "SO TIEN GD < SD TOI THIEU");
		errorCodeMap.put("138", "KHONG CHO PHEP THAU CHI");
		errorCodeMap.put("139", "A/C BRANCH OFFLINE");
		errorCodeMap.put("140", "ACCOUNT HAS SWEEP FACILITY");
		errorCodeMap.put("141", "VUOT HAN MUC RUT LIEN CN");
		errorCodeMap.put("142", "TRANS NOT EVEN MULTIPLE $1000");
		errorCodeMap.put("143", "NGAY DAO HAN > NGAY GD");
		errorCodeMap.put("144", "MA PHI KHONG DUNG");
		errorCodeMap.put("145", "FLOAT RECORD NOT FOUND");
		errorCodeMap.put("146", "INVALID FLOAT STATUS");
		errorCodeMap.put("147", "TXN > MISC COST BY CHRG CD");
		errorCodeMap.put("148", "TXN > OTHR CHRG BY CHRG CD");
		errorCodeMap.put("149", "COUNTER NAME NOT FOUND");
		errorCodeMap.put("150", "LOAI ID KO TIM THAY");
		errorCodeMap.put("151", "GD KO CHO PHEP DOI VOI TK");
		errorCodeMap.put("152", "EXCEED MAX SHARE VALUE ALLOWED");
		errorCodeMap.put("153", "EXCEED AVAIL SHARE UNITS");
		errorCodeMap.put("154", "COLLATERAL ID NOT FOUND");
		errorCodeMap.put("155", "FLOAT DOESN'T BELONG TO BRANCH");
		errorCodeMap.put("156", "SHARE RECORD NOT FOUND");
		errorCodeMap.put("157", "EXCEED CAPITAL PAID UP");
		errorCodeMap.put("158", "NO SHARE FACILITY EXISTS");
		errorCodeMap.put("159", "ADD DEP INVALID - RECEIPT PRTD");
		errorCodeMap.put("160", "QUAN HE DA TON TAI");
		errorCodeMap.put("161", "MA QUAN HE KHONG DUNG");
		errorCodeMap.put("162", "EXCEEDS EXT ACCT TRANS LIMIT");
		errorCodeMap.put("163", "BOP CODE NOT REQUIRED");
		errorCodeMap.put("164", "LOAI TK KHONG KHOP VOI SP");
		errorCodeMap.put("165", "HOST TXCD NOT SAME");
		errorCodeMap.put("166", "HOLDS NOT ZERO FOR CLOSEOUT");
		errorCodeMap.put("167", "NGAY GD KH PHAI LA NGAY TRONG TUONG LAI");
		errorCodeMap.put("168", "SO TIEN GUI < SO DU TOI THIEU");
		errorCodeMap.put("169", "AMOUNT RELEASE < ZERO");
		errorCodeMap.put("170", "NEXT PAYMENT DUE DATE = ZERO");
		errorCodeMap.put("171", "SUBSIDISED BY 3RD PARTY");
		errorCodeMap.put("172", "NOT SUBSIDISED BY 3RD PARTY");
		errorCodeMap.put("173", "OUTSTANDING BAL < ZERO");
		errorCodeMap.put("174", "ORIG FOR LOAN PAY REV INVALID");
		errorCodeMap.put("175", "KHONG DUOC THAY DOI QUAN HE");
		errorCodeMap.put("176", "AMOUNT > ACC PENALTY INT");
		errorCodeMap.put("177", "AMOUNT > INT PAYABLE");
		errorCodeMap.put("178", "SO TT TRONG LKGD TRUNG NHAU");
		errorCodeMap.put("179", "SO TK NHOM TGCKH KHONG DUNG");
		errorCodeMap.put("180", "AMT > PAID LATE CHRG");
		errorCodeMap.put("181", "MUST USE OCP FACILITY");
		errorCodeMap.put("182", "SO TIEN GD > ST GOC");
		errorCodeMap.put("183", "ORIGINAL NOBOOK ITEM NOT FOUND");
		errorCodeMap.put("184", "ODP AUTH LIMIT NOT ZERO");
		errorCodeMap.put("185", "AMOUNT > INTEREST REBATE");
		errorCodeMap.put("186", "AMOUNT > ACCRUED COMMT FEE");
		errorCodeMap.put("187", "FULL CHARGE OFF");
		errorCodeMap.put("188", "SO NGAN HANG KHONG DUNG");
		errorCodeMap.put("189", "SO TIEN LAI RUT PHAI <>0");
		errorCodeMap.put("190", "SO TIEN GD KHONG DUNG");
		errorCodeMap.put("191", "INVALID CPF TRANS AMOUNT");
		errorCodeMap.put("192", "INVALID CPF DATE");
		errorCodeMap.put("193", "TOTAL BILL  AMT <> 09");
		errorCodeMap.put("194", "EFFECTIVE > 1ST DRAWN DOWN");
		errorCodeMap.put("195", "NGAY HIEU LUC KHONG PHAI LA NGAY LAM VIEC");
		errorCodeMap.put("196", "TRN AMT > ALLOWABLE REFUND AMT");
		errorCodeMap.put("197", "REFUND AMOUNT > PRINCIPAL BAL");
		errorCodeMap.put("198", "MAIN ACCOUNT CAN''T PROCESS");
		errorCodeMap.put("199", "KHONG SU DUNG");
		errorCodeMap.put("200", "AMOUNT/CURRENCY LINK INVALID");
		errorCodeMap.put("201", "ID CUA GDV KHONG TON TAI");
		errorCodeMap.put("202", "TXN NOT SUPPORTED");
		errorCodeMap.put("203", "KHONG CHO PHEP THU C HIEN GD");
		errorCodeMap.put("204", "SYSTEM ERROR...CONTACT DP STAFF");
		errorCodeMap.put("205", "TK DA THANH TOAN");
		errorCodeMap.put("206", "SO TK KHONG HOP LE");
		errorCodeMap.put("207", "PASSBOOK BAL IS");
		errorCodeMap.put("208", "NOT A PASSBOOK ACCOUNT");
		errorCodeMap.put("209", "MUST UPDATE PASSBOOK NOW");
		errorCodeMap.put("210", "A/C HAS NO UNPOSTED ITEMS");
		errorCodeMap.put("211", "NOT FOUND WITH GIVEN NAME");
		errorCodeMap.put("212", "LOAN IS PAID OFF");
		errorCodeMap.put("213", "MA DIA CHI KO DUNG");
		errorCodeMap.put("214", "LOAI TIEN KO KHOP");
		errorCodeMap.put("215", "KHONG CHO PHEP XOA");
		errorCodeMap.put("216", "FLOAT NOT ZERO ON CLOSEOUT");
		errorCodeMap.put("217", "HOLDS NOT ZERO ON CLOSEOUT");
		errorCodeMap.put("218", "TK BI DONG HOM NAY");
		errorCodeMap.put("219", "TK DANG SU DUNG BOI GDV KHAC");
		errorCodeMap.put("220", "RENEWAL INVALID ON AUTO-RENEWAL");
		errorCodeMap.put("221", "TK DANG SU DUNG");
		errorCodeMap.put("222", "KO CHO PHEP SO TIEN = 0");
		errorCodeMap.put("223", "TELLER RECORD IN USE");
		errorCodeMap.put("224", "HON 50 LOI DUOC TIM THAY");
		errorCodeMap.put("225", "INT DIST CODE IS INVALID");
		errorCodeMap.put("226", "MA GIA HAN KHONG DUNG");
		errorCodeMap.put("227", "TK CHUYEN DEN SAI");
		errorCodeMap.put("228", "MA GIAO DICH SAI");
		errorCodeMap.put("229", "GD VOI MAY CHU BI GIAN DOAN");
		errorCodeMap.put("230", "CHUA KHOI DONG HANDLER");
		errorCodeMap.put("231", "CHON SAI HANDLER");
		errorCodeMap.put("232", "INVALID CONTROLLER");
		errorCodeMap.put("233", "KHONG CO BAN GHI LICH SU NAO");
		errorCodeMap.put("234", "KHONG TIM THAY BAN GHI NAO");
		errorCodeMap.put("235", "GDV CHUA HOAN THANH GD");
		errorCodeMap.put("236", "DATE VERIFICATION ERROR");
		errorCodeMap.put("237", "UNMATCHED PASSBK SERIAL #");
		errorCodeMap.put("238", "GDV KHONG CO LIET KE GD NAO");
		errorCodeMap.put("239", "CN CHUA CO GIAO DICH NAO");
		errorCodeMap.put("240", "NGAY TIEP THEO KHONG PHAI LA NGAY LAM VIEC");
		errorCodeMap.put("241",
				"NGAY DEN HAN DAU TIEN KO PHAI LA NGAY TUONG LAI");
		errorCodeMap.put("242", "CAC SO SEC NAY DA TON TAI");
		errorCodeMap.put("243", "DAI SO SEC NAY KHONG DUNG");
		errorCodeMap.put("244", "ROUTER TYPE INVALID");
		errorCodeMap.put("245", "ROUTER NOT ACTIVE");
		errorCodeMap.put("246", "POSTDATED DEBITS NOT ALLOWED");
		errorCodeMap.put("247", "MINIMUM WITHDRAWAL");
		errorCodeMap.put("248", "KHONG CHO PHEP RUT MOT PHAN");
		errorCodeMap.put("249", "INVALID SUPER GROUP #");
		errorCodeMap.put("250", "HE THONG DANG THOAT RA");
		errorCodeMap.put("251", "DU LIEU SAI- LIEN HE VOI NHAN VIEN IT");
		errorCodeMap.put("252", "SO TIEN>SO TOI DA CHO PHEP CUA TGCKH");
		errorCodeMap.put("253", "NGAY HIEU LUC NHO HON NGAY PHAT HANH");
		errorCodeMap.put("254", "NGAY HIEU LUC NHO HON NGAY GIA HAN CUOI CUNG");
		errorCodeMap.put("255", "INCOMPLETE RELEASE DOCUMENT");
		errorCodeMap.put("256", "SHORTFALL IN SECURITY DEPOSIT");
		errorCodeMap.put("257", "NOT IJARAH ACCOUNT");
		errorCodeMap.put("258", "EFF DATE BEFORE ORG LOAN DATE");
		errorCodeMap.put("259", "ORIG SHARE TXN DOES NOT EXIST");
		errorCodeMap.put("260", "SHARE UNITS WILL BE NEGATIVE");
		errorCodeMap.put("261", "A/C BAL NOT IN EXCESS");
		errorCodeMap.put("262", "A/C EXCESS BAL IS");
		errorCodeMap.put("263", "SO ID KHONG TIM THAY");
		errorCodeMap.put("264", "SO THAM CHIEU KO DUNG HOAC BI TRUNG");
		errorCodeMap.put("265", "MO TAI KHOAN BI LOI");
		errorCodeMap.put("282", "SO DU GOC KHONG THE = 0");
		errorCodeMap.put("283", "INVALID INSURED PARTY");
		errorCodeMap.put("284", "INVALID PROPOSAL NO.");
		errorCodeMap.put("285", "CUSTOMER - ACCT R/SHIP NOT FOUND");
		errorCodeMap.put("286", "SO TIEN GIAI NGAN PHAI = ST CHO VAY");
		errorCodeMap.put("287", "INVALID LN SUSPENSE ACCT NO");
		errorCodeMap.put("288", "REL AMT EXCEED LOAN SUSPENSE BAL");
		errorCodeMap.put("289", "RETENTION SUM NOT DUE");
		errorCodeMap.put("290", "KHONG NAM TRONG HAN MUC CHO PHEP");
		errorCodeMap.put("291", "TRAN AMT > RETENTION SUM");
		errorCodeMap.put("292", "POST DATED CHEQUE IS NOT ALLOWED");
		errorCodeMap.put("293", "LOI DIEN SWIFT");
		errorCodeMap.put("294", "RM/CHECK NUMBER NOT FOUND");
		errorCodeMap.put("295", "RM NUMBER ALREADY EXIST");
		errorCodeMap.put("296", "RM GROUP NUMBER NOT FOUND");
		errorCodeMap.put("297", "CORR. BANK CODE NOT FOUND");
		errorCodeMap.put("298", "RM A/C IS ALREADY COMPLETED");
		errorCodeMap.put("299", "TRANG THAI SEC DA THAY DOI");
		errorCodeMap.put("300", "QUAN HE DA TON TAI");
		errorCodeMap.put("301", "NGUNG HD CUA SEC NGOAI TE");
		errorCodeMap.put("302", "REMITTANCE IS STOPPED");
		errorCodeMap.put("306", "REMITTANCE STILL NOT ACTIVE");
		errorCodeMap.put("307", "FUNDING <> REMITTANCE AMT");
		errorCodeMap.put("308", "ENCASHMENT <> REMITTANCE AMT");
		errorCodeMap.put("309", "SAI NGAN HANG TRA ");
		errorCodeMap.put("310", "INCORRECT RM GROUP #");
		errorCodeMap.put("311", "RM GROUP NOT VALID FOR PRODUCT");
		errorCodeMap.put("312", "RM NUM & CHECK NUM NOT MATCH");
		errorCodeMap.put("313", "VUOT QUA HAN MUC PHE DUYET");
		errorCodeMap.put("316", "SO TIEN GD KHAC SO TIEN SEC");
		errorCodeMap.put("317", "GIAO DICH GOC KHONG TON TAI");
		errorCodeMap.put("318", "REMITTANCE ALREADY EFFECTIVE");
		errorCodeMap.put("319", "NGAY HIEU LUC QUA XA");
		errorCodeMap.put("320", "SO THAM CHIEU CHUYEN TIEN O DUNG");
		errorCodeMap.put("321", "CHECK STATUS = 1");
		errorCodeMap.put("322", "CHECK STATUS = 2");
		errorCodeMap.put("323", "CHECK STATUS = 3");
		errorCodeMap.put("324", "CHECK STATUS = 4");
		errorCodeMap.put("325", "CHECK STATUS = 5");
		errorCodeMap.put("326", "CHECK STATUS = 6");
		errorCodeMap.put("327", "CHECK STATUS = 7");
		errorCodeMap.put("328", "CHECK STATUS = 8");
		errorCodeMap.put("329", "CHECK STATUS = 9");
		errorCodeMap.put("330", "CHECK STATUS = 10");
		errorCodeMap.put("331", "CHECK STATUS = 11");
		errorCodeMap.put("332", "CHECK STATUS = 12");
		errorCodeMap.put("333", "CHECK STATUS = 13");
		errorCodeMap.put("334", "CHECK STATUS = 14");
		errorCodeMap.put("335", "CHECK STATUS = 15");
		errorCodeMap.put("336", "CHECK STATUS = 16");
		errorCodeMap.put("337", "CHECK STATUS = 17");
		errorCodeMap.put("338", "CHECK STATUS = 18");
		errorCodeMap.put("339", "CHECK STATUS = 19");
		errorCodeMap.put("340", "CHECK STATUS = 20");
		errorCodeMap.put("341", "REMITTANCE STATUS = 7");
		errorCodeMap.put("342", "REMITTANCE STATUS = 8");
		errorCodeMap.put("401", "DAY LA TK CUA NHAN VIEN ");
		errorCodeMap.put("402", "ACCOUNT STATUS CODE N 2");
		errorCodeMap.put("403", "ACCOUNT STATUS CODE N 3");
		errorCodeMap.put("404", "HELLO 55");
		errorCodeMap.put("405", "DANG KIEM TRA");
		errorCodeMap.put("101",
				"THIS TRANSACTION ONLY APPLICABLE TO CAPITALISED LATE CHARGE");
		errorCodeMap.put("409", "ACCOUNT STATUS CODE N 9");
		errorCodeMap.put("410", "ACCOUNT STATUS CODE N 10");
		errorCodeMap.put("411", "ACCOUNT STATUS CODE N 11");
		errorCodeMap.put("412", "ACCOUNT STATUS CODE N 12");
		errorCodeMap.put("413", "ACCOUNT STATUS CODE N 13");
		errorCodeMap.put("414", "ACCOUNT STATUS CODE N 14");
		errorCodeMap.put("415", "ACCOUNT STATUS CODE N 15");
		errorCodeMap.put("416", "ACCOUNT STATUS CODE N 16");
		errorCodeMap.put("417", "ACCOUNT STATUS CODE N 17");
		errorCodeMap.put("418", "ACCOUNT STATUS CODE N 18");
		errorCodeMap.put("419", "ACCOUNT STATUS CODE N 19");
		errorCodeMap.put("420", "ACCOUNT STATUS CODE N 20");
		errorCodeMap.put("421", "ACCOUNT STATUS CODE N 21");
		errorCodeMap.put("422", "ACCOUNT STATUS CODE N 22");
		errorCodeMap.put("423", "ACCOUNT STATUS CODE N 23");
		errorCodeMap.put("424", "ACCOUNT STATUS CODE N 24");
		errorCodeMap.put("425", "ACCOUNT STATUS CODE N 25");
		errorCodeMap.put("426", "ACCOUNT STATUS CODE N 26");
		errorCodeMap.put("427", "ACCOUNT STATUS CODE N 27");
		errorCodeMap.put("428", "ACCOUNT STATUS CODE N 28");
		errorCodeMap.put("429", "ACCOUNT STATUS CODE N 29");
		errorCodeMap.put("430", "ACCOUNT STATUS CODE N 30");
		errorCodeMap.put("431", "ACCOUNT STATUS CODE N 31");
		errorCodeMap.put("432", "ACCOUNT STATUS CODE N 32");
		errorCodeMap.put("433", "ACCOUNT STATUS CODE N 33");
		errorCodeMap.put("434", "ACCOUNT STATUS CODE N 34");
		errorCodeMap.put("435", "ACCOUNT STATUS CODE N 35");
		errorCodeMap.put("436", "ACCOUNT STATUS CODE N 36");
		errorCodeMap.put("437", "ACCOUNT STATUS CODE N 37");
		errorCodeMap.put("438", "ACCOUNT STATUS CODE N 38");
		errorCodeMap.put("439", "ACCOUNT STATUS CODE N 39");
		errorCodeMap.put("440", "ACCOUNT STATUS CODE N 40");
		errorCodeMap.put("441", "ACCOUNT STATUS CODE N 41");
		errorCodeMap.put("442", "ACCOUNT STATUS CODE N 42");
		errorCodeMap.put("443", "ACCOUNT STATUS CODE N 43");
		errorCodeMap.put("444", "ACCOUNT STATUS CODE N 44");
		errorCodeMap.put("445", "ACCOUNT STATUS CODE N 45");
		errorCodeMap.put("446", "ACCOUNT STATUS CODE N 46");
		errorCodeMap.put("447", "ACCOUNT STATUS CODE N 47");
		errorCodeMap.put("448", "ACCOUNT STATUS CODE N 48");
		errorCodeMap.put("449", "ACCOUNT STATUS CODE N 49");
		errorCodeMap.put("450", "ACCOUNT STATUS CODE N 50");
		errorCodeMap.put("451", "ACCOUNT STATUS CODE N 51");
		errorCodeMap.put("452", "ACCOUNT STATUS CODE N 52");
		errorCodeMap.put("453", "ACCOUNT STATUS CODE N 53");
		errorCodeMap.put("454", "ACCOUNT STATUS CODE N 54");
		errorCodeMap.put("455", "ACCOUNT STATUS CODE N 55");
		errorCodeMap.put("456", "ACCOUNT STATUS CODE N 56");
		errorCodeMap.put("457", "ACCOUNT STATUS CODE N 57");
		errorCodeMap.put("458", "ACCOUNT STATUS CODE N 58");
		errorCodeMap.put("459", "ACCOUNT STATUS CODE N 59");
		errorCodeMap.put("460", "TESTXX");
		errorCodeMap.put("461", "ACCOUNT STATUS CODE N 61");
		errorCodeMap.put("462", "ACCOUNT STATUS CODE N 62");
		errorCodeMap.put("463", "ACCOUNT STATUS CODE N 63");
		errorCodeMap.put("267", "FD GROUP WITH CURRENCY EXISTS");
		errorCodeMap.put("98", "SO TT DIA CHI KO THAY");
		errorCodeMap.put("99", "PREVIOUS REST BALANCE WILL < 0");
		errorCodeMap.put("100", "SO TIEN GUI >< SO TIEN GOC");
		errorCodeMap.put("94", "HP/DISCOUNTED/LEASING LOAN");
		errorCodeMap.put("95", "NORMAL/PART. LEAD/BOUGHT LOAN");
		errorCodeMap.put("96", "MCL MAIN ACCOUNT");
		errorCodeMap.put("97", "MCL TRANCHE ACCOUNT");
		errorCodeMap.put("266", "TI GIA MUA BAN NGOAI HOI SAI");
		errorCodeMap.put("268", "SO DU HIEN THOI = 0 ");
		errorCodeMap.put("269", "SO THE TGCKH = 0");
		errorCodeMap.put("270", "AMOUNT > WITHDRAWABLE UNT");
		errorCodeMap.put("271", "SEC DANG BI PHONG TOA");
		errorCodeMap.put("272", "SO TIEN CUA THE> SO TOI DA");
		errorCodeMap.put("273", "LAI SUAT NHO HON LAI SUAT TOI THIEU");
		errorCodeMap.put("274", "LAI SUAT > LAI SUAT TOI THIEU");
		errorCodeMap.put("275", "ADDITIONAL DEP NOT ALLOWED");
		errorCodeMap.put("343", "MA NGAN HANG SAI VOI SEC");
		errorCodeMap.put("344", "CORR AGENT CODE INVALID");
		errorCodeMap.put("345", "MA KHACH HANG DANG KY KO TIM THAY");
		errorCodeMap.put("346", "MA KH CUAR NGUOI HUONG KO TIM THAY");
		errorCodeMap.put("347", "ORG RM ACCOUNT NOT FOUND");
		errorCodeMap.put("348", "STOP INSTRUCTION FOUND");
		errorCodeMap.put("349", "REMITTANCE ALREADY PAID OFF");
		errorCodeMap.put("350", "KHONG CHO PHEP XOA");
		errorCodeMap.put("351", "DD/CO ALREADY EXIST");
		errorCodeMap.put("352", "COLL. ITEM EXIST IN SCHEDULE");
		errorCodeMap.put("353", "RELATED RM INFO EXIST");
		errorCodeMap.put("354", "SO TK KHOAN CHUYEN TIEN LA 0");
		errorCodeMap.put("355", "DUPLICATE COLL. ITEM FOUND");
		errorCodeMap.put("464", "ACCOUNT STATUS CODE N 64");
		errorCodeMap.put("465", "ACCOUNT STATUS CODE N 65");
		errorCodeMap.put("466", "ACCOUNT STATUS CODE N 66");
		errorCodeMap.put("467", "ACCOUNT STATUS CODE N 67");
		errorCodeMap.put("468", "ACCOUNT STATUS CODE N 68");
		errorCodeMap.put("469", "ACCOUNT STATUS CODE N 69");
		errorCodeMap.put("470", "ACCOUNT STATUS CODE N 70");
		errorCodeMap.put("471", "ACCOUNT STATUS CODE N 71");
		errorCodeMap.put("472", "ACCOUNT STATUS CODE N 72");
		errorCodeMap.put("473", "ACCOUNT STATUS CODE N 73");
		errorCodeMap.put("474", "ACCOUNT STATUS CODE N 74");
		errorCodeMap.put("475", "ACCOUNT STATUS CODE N 75");
		errorCodeMap.put("476", "ACCOUNT STATUS CODE N 76");
		errorCodeMap.put("478", "ACCOUNT STATUS CODE N 78");
		errorCodeMap.put("479", "ACCOUNT STATUS CODE N 79");
		errorCodeMap.put("480", "ACCOUNT STATUS CODE N 80");
		errorCodeMap.put("481", "ACCOUNT STATUS CODE N 81");
		errorCodeMap.put("482", "ACCOUNT STATUS CODE N 82");
		errorCodeMap.put("483", "ACCOUNT STATUS CODE N 83");
		errorCodeMap.put("484", "ACCOUNT STATUS CODE N 84");
		errorCodeMap.put("485", "ACCOUNT STATUS CODE N 85");
		errorCodeMap.put("486", "ACCOUNT STATUS CODE N 86");
		errorCodeMap.put("487", "ACCOUNT STATUS CODE N 87");
		errorCodeMap.put("488", "ACCOUNT STATUS CODE N 88");
		errorCodeMap.put("489", "ACCOUNT STATUS CODE N 89");
		errorCodeMap.put("490", "ACCOUNT STATUS CODE N 90");
		errorCodeMap.put("491", "ACCOUNT STATUS CODE N 91");
		errorCodeMap.put("492", "ACCOUNT STATUS CODE N 92");
		errorCodeMap.put("493", "ACCOUNT STATUS CODE N 93");
		errorCodeMap.put("494", "ACCOUNT STATUS CODE N 94");
		errorCodeMap.put("495", "ACCOUNT STATUS CODE N 95");
		errorCodeMap.put("496", "ACCOUNT STATUS CODE N 96");
		errorCodeMap.put("497", "ACCOUNT STATUS CODE N 97");
		errorCodeMap.put("498", "ACCOUNT STATUS CODE N 98");
		errorCodeMap.put("477", "ACCOUNT STATUS CODE N 77");
		errorCodeMap.put("102", "TI GIA HOI DOAI THAY DOI");
		errorCodeMap.put("106", "GUI TIEN LAN DAU KO DUOC TH");
		errorCodeMap.put("107", "GUI TIEN LAN DAU DA DUOC TH");
		errorCodeMap.put("108", "INVALID MIXED TYPE PLACEMENT");
		errorCodeMap.put("103", "ADVANCE PAYMENT MUST NOT LESS THAN ZERO");
		errorCodeMap.put("109", "AMOUNT > ACCRUED LATE CHARGE");
		errorCodeMap.put("358", "CAN DUOC NGUOI KIEM SOAT PHE DUYET");
	}

	public static String getError(String respondCode) {
		return errorCodeMap.get(respondCode);
	}

}
